name: 'Tests'

on:
  pull_request:
    branches: ['main']

jobs:
  builds:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: 'Setup Python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: 'Install packages'
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false
          poetry install
      - name: 'Run tests'
        env:
          REDIS_HOST: localhost
          REDIS_PORT: 6379
        run: 'pytest --exitfirst'